apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: velero
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: setup
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2024-11-05T11-29-45Z
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set minio http://minio.velero.svc:9000 minioadmin minioadmin; do
                echo "Waiting for MinIO..."
                sleep 5
              done
              mc mb --ignore-existing minio/velero-backups
              echo "Bucket created successfully"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
