apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jasencarroll/homelab-gitops.git
    targetRevision: main
    path: infrastructure/actions-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
