apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
  annotations:
    # Sync wave 0 - ArgoCD should be one of the first things deployed
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    # Prevent accidental deletion - requires manual removal
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.0.14
    helm:
      values: |
        global:
          domain: argocd.lab.axiomlayer.com

        configs:
          cm:
            url: https://argocd.lab.axiomlayer.com
            dex.config: |
              connectors:
                - type: oidc
                  id: authentik
                  name: Authentik
                  config:
                    issuer: https://auth.lab.axiomlayer.com/application/o/argocd/
                    clientID: argocd
                    clientSecret: $oidc.authentik.clientSecret
                    scopes:
                      - openid
                      - profile
                      - email
                    insecureSkipEmailVerified: true
                    insecureEnableGroups: true
          rbac:
            policy.default: role:readonly
            policy.csv: |
              # Admin access for jasen user
              g, jasen@axiomlayer.com, role:admin
          params:
            server.insecure: true  # TLS terminated at Traefik

        server:
          replicas: 2
          ingress:
            enabled: false  # Managed separately via ingress.yaml

        repoServer:
          replicas: 2

        redis:
          enabled: true

        dex:
          enabled: true
          replicas: 2

        notifications:
          enabled: true

        applicationSet:
          enabled: true
          replicas: 2

        controller:
          replicas: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # IMPORTANT: Manual sync only to prevent chicken/egg issues
  # Auto-sync disabled - upgrades require explicit manual sync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
