apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.10.2
    helm:
      valuesObject:
        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-helm-secrets
                  key: secret_key
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-db-app
                  key: password
        authentik:
          secret_key: ""  # Set via env var
          postgresql:
            host: authentik-db-rw.authentik.svc
            name: authentik
            user: authentik
            password: ""  # Set via env var
        postgresql:
          enabled: false
        redis:
          enabled: true
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - auth.lab.axiomlayer.com
            tls:
              - hosts:
                  - auth.lab.axiomlayer.com
                secretName: authentik-tls
          volumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
        worker:
          volumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
