apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.10.2
    helm:
      valuesObject:
        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-helm-secrets
                  key: secret_key
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-db-app
                  key: password
        authentik:
          secret_key: ""  # Set via env var
          postgresql:
            host: authentik-db-rw.authentik.svc
            name: authentik
            user: authentik
            password: ""  # Set via env var
        postgresql:
          enabled: false
        redis:
          enabled: true
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - auth.lab.axiomlayer.com
            tls:
              - hosts:
                  - auth.lab.axiomlayer.com
                secretName: authentik-tls
          volumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
        worker:
          volumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
        # Service account for outpost management
        serviceAccount:
          create: true
        # RBAC for deploying outposts to Kubernetes
        rbac:
          create: true
          createClusterRole: true
          clusterRoleRules:
            - apiGroups: [""]
              resources: ["namespaces", "pods", "services", "secrets", "configmaps", "serviceaccounts"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["apps"]
              resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["networking.k8s.io"]
              resources: ["ingresses"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["rbac.authorization.k8s.io"]
              resources: ["roles", "rolebindings"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs: ["list"]
            - apiGroups: ["traefik.io", "traefik.containo.us"]
              resources: ["middlewares"]
              verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
