apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/jasencdev/axiomlayer.git
    targetRevision: main
    path: infrastructure/cloudnative-pg
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # Manual sync only - critical database infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
