apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      skipCrds: false
      values: |
        # Global tolerations for control-plane nodes
        global:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        persistence:
          defaultClassReplicaCount: 2
        defaultSettings:
          defaultReplicaCount: 2
          replicaSoftAntiAffinity: false
          replicaAutoBalance: best-effort
          backupTarget: nfs://192.168.1.234:/volume/e8e70d24-82e0-45f1-8ef6-f8ca399ad2d6/.srv/.unifi-drive/Shared_Drive_Example/.data?nfsOptions=nfsvers=3,nolock
        preUpgradeChecker:
          jobEnabled: false
        longhornManager:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
        longhornDriver:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
        csi:
          attacherResources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
          provisionerResources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
          resizerResources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
          snapshotterResources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
        - .metadata.labels
        - .spec.conversion
    - group: longhorn.io
      kind: Setting
      jsonPointers:
        - /value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
