apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jasencdev/axiomlayer.git
    targetRevision: main
    path: infrastructure/nfs-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
