apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane-extras
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jasencarroll/homelab-gitops.git
    targetRevision: main
    path: apps/plane
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
