apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: 1.4.0
    helm:
      releaseName: plane
      values: |
        planeVersion: stable

        ingress:
          enabled: true
          appHost: plane.lab.axiomlayer.com
          ingressClass: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"

        ssl:
          createIssuer: false
          generateTLS: true
          secretName: plane-tls

        postgres:
          local_setup: true
          volumeSize: 10Gi
          storageClass: longhorn

        redis:
          local_setup: true
          volumeSize: 1Gi
          storageClass: longhorn

        rabbitmq:
          local_setup: true
          volumeSize: 1Gi
          storageClass: longhorn

        minio:
          local_setup: true
          volumeSize: 10Gi
          storageClass: longhorn

        env:
          docstore_bucket: "uploads"
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: plane-ingress
      jsonPointers:
        - /spec/tls
        - /metadata/annotations/traefik.ingress.kubernetes.io~1router.entrypoints
        - /metadata/annotations/traefik.ingress.kubernetes.io~1router.tls
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
