apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: 1.4.0
    helm:
      releaseName: plane
      values: |
        planeVersion: stable

        ingress:
          enabled: true
          appHost: plane.lab.axiomlayer.com
          ingressClass: traefik
          ingress_annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"

        ssl:
          tls_secret_name: plane-tls

        postgres:
          local_setup: true
          volumeSize: 10Gi
          storageClass: longhorn

        redis:
          local_setup: true
          volumeSize: 1Gi
          storageClass: longhorn

        rabbitmq:
          local_setup: true
          volumeSize: 1Gi
          storageClass: longhorn

        minio:
          local_setup: true
          volumeSize: 10Gi
          storageClass: longhorn

        worker:
          memoryLimit: 2000Mi
          memoryRequest: 500Mi

        env:
          docstore_bucket: "uploads"
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
