apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.1.0
    helm:
      releaseName: velero
      values: |
        kubectl:
          image:
            repository: bitnami/kubectl
            tag: "latest"

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.11.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: true
                s3Url: http://minio.velero.svc:9000
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: minio

        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=minioadmin
              aws_secret_access_key=minioadmin

        deployNodeAgent: true

        schedules:
          daily-backup:
            disabled: false
            schedule: "0 2 * * *"
            template:
              ttl: "168h"
              includedNamespaces:
                - "*"
              excludedNamespaces:
                - kube-system
                - velero
              storageLocation: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
