apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: SealedSecret is the K8s representation of a "sealed Secret" - a regular k8s Secret that has been sealed (encrypted) using the controller's key.
          type: object
          required:
            - spec
          properties:
            apiVersion:
              description: APIVersion defines the versioned schema of this representation of an object.
              type: string
            kind:
              description: Kind is a string value representing the REST resource this object represents.
              type: string
            metadata:
              type: object
            spec:
              description: SealedSecretSpec is the specification of a SealedSecret
              type: object
              required:
                - encryptedData
              properties:
                data:
                  description: Data is deprecated. Use per-value EncryptedData instead.
                  type: string
                  format: byte
                encryptedData:
                  type: object
                  additionalProperties:
                    type: string
                  x-kubernetes-preserve-unknown-fields: true
                template:
                  description: Template defines the structure of the Secret that will be created.
                  type: object
                  properties:
                    data:
                      type: object
                      nullable: true
                      additionalProperties:
                        type: string
                    metadata:
                      type: object
                      nullable: true
                      x-kubernetes-preserve-unknown-fields: true
                      properties:
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                        finalizers:
                          type: array
                          items:
                            type: string
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    type:
                      description: Used to facilitate programmatic handling of secret data.
                      type: string
            status:
              description: SealedSecretStatus is the most recently observed status of the SealedSecret.
              type: object
              properties:
                conditions:
                  description: Represents the latest available observations of a sealed secret's current state.
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                observedGeneration:
                  type: integer
                  format: int64
