apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: campfire
  namespace: campfire
  labels:
    app.kubernetes.io/name: campfire
    app.kubernetes.io/component: chat
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: campfire
