apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campfire-storage
  namespace: campfire
  labels:
    app.kubernetes.io/name: campfire
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
