apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authentik-outpost-management
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
rules:
  # Core resources for outpost deployment
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "secrets", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Deployment management
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Ingress management
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # RBAC for outpost service accounts
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # CRD discovery
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list"]
  # Traefik middleware for forward auth
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["middlewares"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authentik-outpost-management
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authentik-outpost-management
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: authentik
