apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: outline
  namespace: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/component: wiki
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: outline
