---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    "client-id": AgCka7rFjeoWcR7mJIhod+uk4GwDOPMEYvgceoR59SMreuyeXF+eyl9P8tDWewzuuSwn+ZjLcnnYIl/uCt65HadweFebT1OAP6LI2m9cEspYwEM/n5+Cg9wBasMoMkLZKp61xXoWRX5kXq0+ih29ytWVhFcgUlgBf8NbkyJk5Ih0WbHGZ1a4xUXSvNCWEpCs1tnL0xuV8G9nUpFrgtSvw3AW01ESxboLiDyAKGBDKOSl4oDZYB0AojaZYCNeBjzanMO20D5ejVCKMqD3fik69UqQ+uW/pWMLVuIDnCXOiVX2umwX5hyONL+zIN1mribeAOHCBYRxKLFn68Bc1ypeW7hXWTh6TqJpRI1P7G78x6i+gkBQH7iXqgva317f2Oyt8rxYxp5IpHIlfvmYISeyAobGU3mL7i/MYFeEkTE9uyinz0qApPCrgdXotqAtTzFYV3wd9MQYbi0Z05C1DaNlYRRYlYtM3JqSvxjxCmmCDmPne2SoKzK/J3yqJuVbYtU3bbod6G4gbvVLYVIXOT5lc1XSTaB5XUS81ibix6Ga/dZRKcGGxaUg+HDat4dotQaPiQiYM1cafcwK13T+e24oKVBNcXyIg0Ji9g3M2wQBEmzh4r6f65/U6XW/73ymFiHFaJ7mwaWjfTrtMH8OgGdvG/rFScRcL6CZN0uvGzudQU5rTqSx2PkvGRnWmOR1DoReKkC/DFSTzNiq
    "client-secret": AgAtK719RvEld+feuOQSWlQu7uTqRynYdfQ4fMjbkZMxuUXCFlDelmnKttpRDBwOQ7B/bDjyMxSmrsqTyTmxMIXezG5bW3ESX5r+ObbLq5biiegQz4npMoZds8ff8kuwwZu+GNpggFSF2Zt4TCe8x64ZjlBkWtPSmlIbGR8rf55kvlzFH1+CvGNw//THzVJI7DBpdDqkBmr6bQFwAPC0nh4YJo3OCsLIKaIrlnVDrSe876juRT7IBuvQMWSWOIU2xtpMQyHUV/wgOhey8wEk39cVuSQpLMaWKDw0y1MyfDRwnPIDjQ+/t7qWTOLky8/AaPT4SfFSUdsMEwJ1pL7M6voCdUXIsdog9/aJMay3fQOVS3aU9AWWu446QdY0Ls2QtjM/dk+qt8yxAe/Qw5i5qJ+WCe6Sy5ese2w1EsGfQnysRCHyiOn+SaVaCjcJ6onrU6M3vhMj04NWdzo2FfIrOHDy9y6aBz3ZJ5TbiB3Ygvc+ey+d/LqjKuRFpBkbu+OXBPgDJfMnRBozsZlJnVJRAl9mPiZ+zv78oeNre0Nr0jeCnQF3EjByU6LU/RfNz2siAuC6aQEJOlTaOdjHcgcI2gZcp9QuuPcC8fjG44poGW6XbeQ+pa2z7KAx04jWBB2EnM83sBo2qZrKSOruYnN9svmSl0GC1qwRaGu385stK3lTC7cGUR6NaCBkYl54gzmUKt3kZXMKGc3+9PwA+vhFIKfUdhBEovK0jvQsL15hr2lVaYwrP+xxYbobpQG/TDnnam7qdII5LztEYC2I/su+PbZoJdExx2iXNSuttIzFgGvB7PxYbXtdVbyEtYEvq7d1VqnV7RFv5QHrur+Ayc0lURhQuIxv1W17PxTT8iq1SBBLEA==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque
