# NOTE: Do not commit actual secrets to git
# Create this secret manually or use sealed-secrets
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  oidc.authentik.clientSecret: REPLACE_ME
