# Automated Backup CronJob
# Backs up Authentik and Outline databases to NAS via nfs-proxy
apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-backup
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: homelab-backup
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  schedule: "0 3 * * *"  # 3 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
      template:
        metadata:
          labels:
            app.kubernetes.io/name: homelab-backup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: backup-sa
          nodeSelector:
            kubernetes.io/hostname: neko
          containers:
            - name: backup
              image: postgres:16-alpine
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  DATE=$(date +%Y%m%d-%H%M%S)
                  BACKUP_DIR="/backup/homelab-$DATE"
                  mkdir -p "$BACKUP_DIR"

                  echo "=== Homelab Backup - $DATE ==="

                  # Backup Authentik DB
                  echo "Backing up Authentik database..."
                  PGPASSWORD="$AUTHENTIK_DB_PASSWORD" pg_dump \
                    -h authentik-db-rw.authentik.svc \
                    -U authentik \
                    -d authentik \
                    > "$BACKUP_DIR/authentik-db.sql"
                  echo "  ✓ Authentik: $(wc -l < "$BACKUP_DIR/authentik-db.sql") lines"

                  # Backup Outline DB
                  echo "Backing up Outline database..."
                  PGPASSWORD="$OUTLINE_DB_PASSWORD" pg_dump \
                    -h outline-db-rw.outline.svc \
                    -U outline \
                    -d outline \
                    > "$BACKUP_DIR/outline-db.sql"
                  echo "  ✓ Outline: $(wc -l < "$BACKUP_DIR/outline-db.sql") lines"

                  # Cleanup old backups (keep last 7)
                  echo "Cleaning up old backups..."
                  cd /backup && ls -dt homelab-*/ 2>/dev/null | tail -n +8 | xargs -r rm -rf

                  echo "=== Backup Complete ==="
                  ls -lh "$BACKUP_DIR"
              env:
                - name: AUTHENTIK_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backup-db-credentials
                      key: authentik-password
                - name: OUTLINE_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backup-db-credentials
                      key: outline-password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          volumes:
            - name: backup-storage
              nfs:
                server: nfs-proxy.nfs-proxy.svc.cluster.local
                path: /
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: homelab-backup
    app.kubernetes.io/part-of: homelab
