---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgAuu+NjZCEqrqMpKRUF+/ou+K3oWjJRnuBUXw6ICGFpo2oP47k3vM3lp9v7fD98S5JSW54ZskpunRhUzpD6/b6FQ/WvKWLbHjSnhTrBQNcTVsaLZo4sLDEFfnJCJ03iE5Rh7JWDq2tu2UpIHPiLQrE8vaL+kIVPZhZA7NLNXhtom4sAcyFEG3wom5Awy9bUBhti1UJ8moFA2nIUXkr4l96eg7x8qXV4WGZvdCMl6ofCiOWfnXx1M3c1p+MnK8OpN/9KxRgpIwVwMFuhS9fdZnh7ii390CbiJbnqBUk32UOHiPgPifUptuNiQtSQx7L+7t+Q/eftPAMlKL+/4ZLRrieEtsGm5JAfFBX8Na3tM/lu9uOOHXy9rxWl270u2qhaUs1rugiuqTFPsTPvxmTGTZA1A+Tpmub9vA7/p0y3Bny0cFIhyGbUxOh7MpoG+ucyqmm658kAPEIUYKwuH0Rn2kteLy+fMvkde7Op90Gb8vezbcYVhm6wrZsv4otnrzu/gF+yndYCHm9Z4SbFEifMcExNfIDSeMBPSUck132qI4ThU4KuXZwbk586KjoeQJVEX9cDBv31XLtdVjvle0XO37T0TsPmZcw/L/iwZztaVjxlpKxowMytdUnRgpaCpeZvqN4p/e/4p7GxhXElkeauJx6u5VWiyBy4M0WB1UNYe+YwrwBYSGxM1JMxM+UJ9PhUJOdIblx2HCSB92pXyVWsiQm7pQ5AMhfangiXvuz1Tg==
    root-user: AgASE6BNDje2idwkOEztiJP48gEKehdPHy4sn/naVde5oml8XLxvig0J8W/xld/sBuRTY+C8N5MZfeH/gFNvPQQD4UR5tnqUknqbrYj8MXtzv9h2Jfc7XJ0XwtqZrMXrm4abawJFKH8X76b4iBfjniu3cU3Ti9r2Raq7H/VNdpnImqEhBDf6p94QLeMWsydOkQ6ePsScwOMh1wuueMHqtyKcdBOALq8t3tTG1mspNAcb5OKTU62bl2HkVtUbFka3GkgnyjmEkffRIbipT7h3YV7gCceQ1WJt3+9kgkpkflYs7SBMq7/60gJ/QnEDxHpOmXuKe2+DxzM0ZUWzyiKDReXUt4euXOwSlQ3pMnd0Zsp9PUjeL+B3tob3QeLEIXnkEF+IOMkguVcvVnPQLRN9WNDJvDfD5hwSnVAUr+WMURf9t/O11rr0+wGKqkTa6Yi8KAg5u11CfOCZIds2GsyeYXSjJ097hshI8P/4B/xef/Yhq8lD5NgelpS/cTnduLSaDQxw5i5F4SWUy/H6jAeZiX3/Kqm1/sQdVJ8VnM8DRsK3jKc77hGpHCi+B9bbqgKLconDjFNiAhB59aXrWSYVnWlkUkIf5nniZuhrrmejREsXbs4ANkxkj59II9m3ZvjjukBbqi83vwWRuCD7ZLqPJICDHRnnrWWvK/IJLVUAbt3ls6XTffctMvbjt/FFI+bj4+lQC3KNHSld3Bml8A==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
