---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAEM3jLtqwIkwvADv9IEY0q87fpAEvAPriWinHeWDDFBzRWoGntKWzjo34gVNarrQ/9RabBoAPAJkuMej1WlI7VA1na0/S7VaJxNW9lkPOjKUksibeacgBxMycMQgIr484/KPxPwf0sL4ihpL9ksSBYr3DEMarC/CGLdJe7xIAL/b0fImWGBjUqT4Xgoyl1M3uPrvCsxO7N5iRA8x19HQcEYyAwj1/VkDanUTmjJdDU5xcjsQhgEPb3O95ndAt4kNZCFuPKt6eJXmO+Uqi8tOE8dAZ106FZAGjWFxmGGtSEB43bmhT4Bdy5R1bfVdkBV97wllhj5hvh093TJRmecWE6MOOzuNuwBcwenKb8o8laLAzXZ5lhfAkL4J059bC7hPUTSrj+5PFzIM/IGOp+35csSsmS1vIRUR+knQr3t0UlQl1Jsv6ro6Au6lm3YOiDU7krXh+vcTcLdf4wIZch8pMxu9yVFn4fcBNGlUOMszuX5jj6quly6pzbGoOGyFm2UyIBs29H8t+5CIfMUisCSbqOeeR9843NDjiYAPTHErwyJ9tS0VWqnMCHoCtJmtREuOJs/GhJ/4nfgAqPRkdQAtgnrp1adCvaDCBxi+fswIJH5PETO+6VxVNQRdqXNxoYlQ/2EMK6VP1qeJNCU4aJBYkm0/zZCjpX+ZgGUddixot+B4WPKHqu1VgLmpaSe+W3ibuhFtjp95nBR+kE8pEkBPu7QZTAMge53sqUMECAhW+i479qi1nzXxDv
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
