apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: ai-interface
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: open-webui
