apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: open-webui-db
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  instances: 2

  affinity:
    podAntiAffinityType: required
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  storage:
    size: 10Gi
    storageClass: local-path

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: openwebui
      owner: openwebui

  monitoring:
    enablePodMonitor: true
